### ISSUE TITLE
Rethink inclusion of `manifest.json` inclusion in scaffold

### ISSUE THREAD

**Issue by fabiankaegy** [10up/wp-scaffold#118]
One thing I've noticed again and again over the past few years is that the default values in the `manifest.json` file don't get changed. Most sites don't require it and don't get built as PWA's at this point. And since more browsers started using the `theme_color` for styling bits of their UI this can lead to unfortunate visuals. 

https://github.com/10up/wp-scaffold/blob/ce3177347c810bd0cba5f18e9de45afba499eef9/themes/10up-theme/manifest.json#L9

| iOS | macOS |
|-----|--------|
|![Simulator Screen Shot - iPhone 12 - 2022-05-03 at 08 23 49](https://user-images.githubusercontent.com/20684594/166412263-8db408f9-f4dc-4b1e-ba56-595ebbde78c1.png)|![CleanShot 2022-05-03 at 08 27 26@2x](https://user-images.githubusercontent.com/20684594/166412520-aebdf821-f248-46e0-98e9-cd361965e4da.png)|

If used correctly the `theme_color` is very useful. But currently, I think that it more often gets "forgotten" and stays with the default value which is creating a bad experience.

**Comment by dainemawer** [comment]
@fabiankaegy I tend to agree with you here. `theme-color` can be used as a `<meta />` tag in the `<head>` if so desired. 

Icons, can also be easily linked to the document using a combination of `<meta />` tags and the `site.webmanifest` (at least for Windows). 

+1 for removing `manifest.json` unless we intend to setup a PWA
