### ISSUE TITLE
includes/blocks/blocks.js on Package.json

### ISSUE THREAD

**Issue by smy315** [10up/wp-scaffold#12]
On package.json (https://github.com/10up/wp-scaffold/blob/trunk/themes/10up-theme/package.json#L27), there is a blocks entry (includes/blocks/blocks.js) but this does not exists on the includes folder. Unless I'm missing something, this entry should be removed or file is missing.

Maybe instead of needing to add index.js for each custom block on package.json like on https://github.com/10up/wp-scaffold/blob/trunk/themes/10up-theme/package.json#L36, have includes/blocks/blocks.js that imports them all so that package.json doesn't need to be updated every time a custom block is added?

**Comment by ryanwelcher** [comment]
@smy315 we need an entry point for each block to be able to reference it in the [block.json](https://github.com/10up/wp-scaffold/blob/trunk/themes/10up-theme/includes/blocks/example-block/block.json#L18) file for that block. 

The `register_block_type_from_metadata` call in the r[egister.php](https://github.com/10up/wp-scaffold/blob/trunk/themes/10up-theme/includes/blocks/example-block/register.php#L18) file actually handles enqueuing the assets based of the `editorScript` entry in block.json.

**Comment by smy315** [comment]
@ryanwelcher got it. Closing this out.
