### ISSUE TITLE
TenUpToolkit\set_dist_url_path() function referenced but does not exist.

### ISSUE THREAD

**Issue by PypWalters** [10up/wp-scaffold#120]
### Describe the bug

This function (`TenUpToolkit\set_dist_url_path`) does not exist in the wp-scaffold code base. We should either add the function or remove the 2 function calls.

### Steps to Reproduce

The function is wrapped in a conditional that would most likely not be true in most cases. The function is referenced in these 2 locations:
- https://github.com/10up/wp-scaffold/blob/4b7fe407b50b8fa16d6650f32caf56bff83eb334/mu-plugins/10up-plugin/plugin.php#L11
- https://github.com/10up/wp-scaffold/blob/4b7fe407b50b8fa16d6650f32caf56bff83eb334/themes/10up-theme/functions.php#L20

If you search the codebase for the function you will not find it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joesnellpdx** [comment]
@PypWalters 

The function exists as part of 10up-toolkit

Can be found here: https://github.com/10up/10up-toolkit/blob/fd8b7ec9c0a4f7c22174608852d9c38dcbe37282/packages/toolkit/config/fast-refresh.php


More info here: https://github.com/10up/10up-toolkit/blob/fd8b7ec9c0a4f7c22174608852d9c38dcbe37282/packages/toolkit/README.md#basic-setup

CC: @nicholasio

**Comment by nicholasio** [comment]
That's right, this file is created at build time by toolkit and it's what power hot mode reloading/fast refresh. It's only ever loaded when running locally. Toolkit also does not create that file when building for production

**Comment by PypWalters** [comment]
Ah, that makes sense! Thanks for the info. Maybe we could add some comments around that part of the code to give some context?
