### ISSUE TITLE
Code Standards: Use long-form array syntax when declaring arrays

### ISSUE THREAD

**Issue by roseg43** [10up/wp-scaffold#157]
### Is your enhancement related to a problem? Please describe.

As per the [WordPress PHP Coding Standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#declaring-arrays), arrays should be declared using `array()` syntax. If we're following these standards, we should identify any instances where we're declaring arrays using shorthand syntax and convert them to the long-form version.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thexavismith** [comment]
@roseg43 why long form syntax? It's common to use the short form array syntax in JavaScript. I'd say being able to use the same syntax across languages to accomplish similar things makes things more accessible. All this to say, please let me keep my brackets 🤣

**Comment by roseg43** [comment]
@smithtimmytim 😆 It's because scaffold uses the 10up - Default phpcs ruleset via https://github.com/10up/phpcs-composer. This ruleset extends https://github.com/WordPress/WordPress-Coding-Standards, and the WPCS states:

> Using long array syntax ( array( 1, 2, 3 ) ) for declaring arrays is generally more readable than short array syntax ( [ 1, 2, 3 ] > ), particularly for those with vision difficulties. Additionally, it’s much more descriptive for beginners.
>
> Arrays must be declared using long array syntax.

I linked the rule in the issue description if you want to explore more!

**Comment by pabamato** [comment]
@roseg43 the 10up-wp-scaffold uses 10up-default PHP coding standards which extends WordPress core standards and allows short array syntax.
See: https://github.com/10up/phpcs-composer/blob/master/10up-Default/ruleset.xml#L61

**Comment by darylldoyle** [comment]
I'm going to close this issue. 

Whilst Core still requires the long array syntax, the 10up PHPCS rules specifically allow the short array syntax.

https://github.com/10up/phpcs-composer/blob/2d03ba19ad5259275aa4f2287340e3d7d270196b/10up-Default/ruleset.xml#L72-L73

I feel that _most_ engineers now lean towards using the short array syntax, so changing that seems like it will add a bunch of overhead for no real gain.
