### ISSUE TITLE
Standardize structure for block styles, variations, extensions, filters etc. in the Theme Scaffold

### ISSUE THREAD

**Issue by saltcod** [10up/wp-scaffold#18]
Adding block styles is an extremely common pattern out in the "wild". Block variations are becoming more common as well. 

I think it would be valuable to outline structure for core block styles and variations in the new theme. 

Perhaps these could live here:

```
/includes
	/blocks
		/core-blocks	
			/styles
			/variations
			/filters

```
I think block styles and variations have the same importance as the example-block we're enqueuing. It would be worth adding this structure to pave the way for showing people where to put these things, even if all of the code was commented out.

**Comment by fabiankaegy** [comment]
The structure has already been added in #19
