### ISSUE TITLE
Error: Cannot find module '@10up/babel-preset-default' on clean install

### ISSUE THREAD

**Issue by jamesmorrison** [10up/wp-scaffold#187]
### Describe the bug

Running the `npm run build` command in the root directory fails with this error:

```
> tenup-wp-scaffold@1.0.0 build
> npm run build --workspaces --if-present


> tenup-theme@1.0.0 build
> 10up-toolkit build

node:internal/modules/cjs/loader:988
  throw err;
  ^

Error: Cannot find module '@10up/babel-preset-default'
Require stack:
- /Users/jamesmorrison/Sites/wp/src/wp-content/node_modules/10up-toolkit/config/webpack/modules.js
- /Users/jamesmorrison/Sites/wp/src/wp-content/node_modules/10up-toolkit/config/webpack/index.js
- /Users/jamesmorrison/Sites/wp/src/wp-content/node_modules/10up-toolkit/config/webpack.config.js
- /Users/jamesmorrison/Sites/wp/src/wp-content/node_modules/10up-toolkit/scripts/build.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at module.exports (/Users/jamesmorrison/Sites/wp/src/wp-content/node_modules/10up-toolkit/config/webpack/modules.js:86:19)
    at Object.<anonymous> (/Users/jamesmorrison/Sites/wp/src/wp-content/node_modules/10up-toolkit/config/webpack.config.js:65:10)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jamesmorrison/Sites/wp/src/wp-content/node_modules/10up-toolkit/config/webpack/modules.js',
    '/Users/jamesmorrison/Sites/wp/src/wp-content/node_modules/10up-toolkit/config/webpack/index.js',
    '/Users/jamesmorrison/Sites/wp/src/wp-content/node_modules/10up-toolkit/config/webpack.config.js',
    '/Users/jamesmorrison/Sites/wp/src/wp-content/node_modules/10up-toolkit/scripts/build.js'
  ]
}
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: tenup-theme@1.0.0 
npm ERR!   at location: /Users/jamesmorrison/Sites/wp/src/wp-content/themes/10up-theme 
```

### Steps to Reproduce

1. Clone this repo (it doesn't technically have to be in a WP install)
2. Navigate to the repo root
3. Run `npm install`
4. Run `npm run build`
5. This error appears consistently

Note: Until this morning, I'd not seen this issue, it was first noted in a failed build on a project that used this as a template; however no changes had been made since this was last working.

### Screenshots, screen recording, code snippet

![Screenshot of error](https://github.com/10up/wp-scaffold/assets/141750/6b32a0e0-c9d1-4774-a4f6-aa64bb969d29)

### Environment information

Device: Mac Studio (issue was also noted on Gitlab Runners on Ubuntu)
OS: MacOS
Shell: ZSH
Application: iTerm2

### WordPress information

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
That's odd. Looks like there were a few releases in NPM that broke things. 🤦

**Comment by darylldoyle** [comment]
@nicholasio, can this be fixed from 10up-toolkit, or is it something that we _need_ to include here? My concern with including them here is we then end up with build dependencies split between 10up-toolkit and project code, which is going to make upgrading 10up-toolkit in the future a nightmare.

I'd much rather not include the override here if we can.

**Comment by nicholasio** [comment]
FYI @darylldoyle @jamesmorrison I did not run into this issue after updating toolkit https://github.com/10up/wp-scaffold/pull/189.

**Comment by fabiankaegy** [comment]
Marking this as closed for now since it seems toolkit handled this
