### ISSUE TITLE
Bump Node versions

### ISSUE THREAD

**Issue by tobeycodes** [10up/wp-scaffold#200]
Even if versions as low as 12 will work I don't think we should encourage it. I imagine there are some edge cases where things do not work on these versions.

https://github.com/10up/wp-scaffold/blob/trunk/themes/10up-theme/package.json#L16

I recommend that we bump everything to the latest LTS and consider enabling engineStrict if possible

**Comment by fabiankaegy** [comment]
Good catch. This was an oversight #202 

I agree we should look at updating to 18 or even 20 but that's a separate thing
