### ISSUE TITLE
PHPCS Broken

### ISSUE THREAD

**Issue by darylldoyle** [10up/wp-scaffold#219]
### Describe the bug

Since #206 was merged, PHPCS has been broken on commit. This is because it moved the lintstaged config to the theme & plugin and they don't contain the PHPCS config, nor the executable. 

We should either:

1. Find a way to allow PHP linting to run from the root, whilst allowing eslint to use the configs from each directory
2. Revert the lintstaged change for now
3. Install and configure PHPCS and it's rules within each directory (but this adds a lot of config overhead)

### Steps to Reproduce

* Clone the repo.
* Make a change within a PHP file.
* Commit.
* See PHPCS error in the pre-commit hook.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
![image](https://github.com/10up/wp-scaffold/assets/6104632/820e1e87-0443-44e1-96d7-caa37fefeddd)
We can just point to phpcs in root.

I did and got this other error, I think it's related to php version not phpcs itself.

**Comment by johnwatkins0** [comment]
Exactly as @nicholasio mentioned, modifying the theme/plugin lint staged files like so fixed this for me:

```
...
    "*.php": [
      "../../vendor/bin/phpcs --extensions=php --warning-severity=8 -s"
    ]
```

Related -- is the lintstaged file in the root still needed?

**Comment by nicholasio** [comment]
> Exactly as @nicholasio mentioned, modifying the theme/plugin lint staged files like so fixed this for me:
> 
> ```
> ...
>     "*.php": [
>       "../../vendor/bin/phpcs --extensions=php --warning-severity=8 -s"
>     ]
> ```
> 
> Related -- is the lintstaged file in the root still needed?

It would be the default one, if there's a plugin/theme without a lintstaged file it would fallback to the root one and therefore use the global eslint config. So I think it makes sense to leave it there.
