### ISSUE TITLE
Lint-staged assumes you have 10up-toolkit installed globally

### ISSUE THREAD

**Issue by johnwatkins0** [10up/wp-scaffold#220]
### Describe the bug

In a fresh clone of the scaffold, on a newish laptop where I have never installed 10up-toolkit globally, my initial commit fails because the commands in .lintstagedrc.json assume 10up-toolkit is available globally. I'm not sure this repository should assume 10up-toolkit is available globally, and I think it's a better practice to use the local copy of the script anyway so that the lintstaged results are aligned with the results in your code editor and CI processes.

### Steps to Reproduce

1. Clone the repo in an environment where 10up-toolkit is not installed globally
2. `npm install` to set up husky and lint-staged
3. Run a commit and see the errors
4. Install 10up-toolkit globally, commit again, and see that 10up-toolkit runs as expected (with linting errors as of today, but that's a separate issue)

### Environment information

Node 20 / NPM 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
Has anyone else being able to reproduce this?

**Comment by darylldoyle** [comment]
@nicholasio I haven't been able to replicate this either. My version always uses the local version as I don't have it installed globally 🤔 

![image](https://github.com/10up/wp-scaffold/assets/968731/815c4300-9b9c-4f80-b881-ee2e794dbf20)

![image](https://github.com/10up/wp-scaffold/assets/968731/d72eaa43-48c8-4de8-aeee-31612bd1ea21)

**Comment by darylldoyle** [comment]
Closing this out as we've not had any more reports of this.
