### ISSUE TITLE
Fix initial linting errors in the scaffold

### ISSUE THREAD

**Issue by johnwatkins0** [10up/wp-scaffold#221]
### Describe the bug

On a clean installation of the scaffold, after running npm install, running an initial commit is blocked because of linting errors in the theme, specifically 3 CSS errors.

I suggest fixing these errors or at least adding ignore comments to them so that an initial commit can be made without friction.

### Steps to Reproduce

1. Make a clean install of the scaffold
2. Run `npm install`
3. Make a commit and you'll see lint staged failing due to several CSS errors

### Environment information

Node 20 / NPM 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by claytoncollie** [comment]
Related to #262
