### ISSUE TITLE
Downstream dependencies require node 20, not 18

### ISSUE THREAD

**Issue by dustinrue** [10up/wp-scaffold#231]
### Describe the bug

When trying to install @wordpress/create-block (at least) requires node 20 but the .nvmrc file defines 18.

```
Now using node v18.20.3 (npm v10.7.0)
npm error code EBADENGINE
npm error engine Unsupported engine
npm error engine Not compatible with your version of node/npm: @wordpress/create-block@4.43.0
npm error notsup Not compatible with your version of node/npm: @wordpress/create-block@4.43.0
npm error notsup Required: {"npm":">=10.2.3","node":">=20.10.0"}
npm error notsup Actual:   {"npm":"10.7.0","node":"v18.20.3"}
```

Modifying .nvmrc to spec node 20 allows the install to complete but I don't know if it causes any other issues. Additionally, the README says node 16 or greater is required.

### Steps to Reproduce

1. Have the latest release of WP Scaffold
2. Use nvm install/use
3. run npm install

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by darylldoyle** [comment]
Fixed in #253
