### ISSUE TITLE
Update Node to latest LTS

### ISSUE THREAD

**Issue by tobeycodes** [10up/wp-scaffold#242]

**Comment by darylldoyle** [comment]
@nicholasio does this align with 10up toolkit?

**Comment by tobeycodes** [comment]
It looks like toolkit accepts 16 and up https://github.com/10up/10up-toolkit/blob/develop/packages/toolkit/package.json#L99

https://nodejs.org/en/about/previous-releases

I think we should bump that too. With NVM, an .nvmrc and packge.json engines it's very easy to switch between versions even if older projects require older versions. I have had to work on some projects recently on Node 8 and 12 and they were hard to get working.
