### ISSUE TITLE
Remove magic $n function

### ISSUE THREAD

**Issue by tobeycodes** [10up/wp-scaffold#246]
https://github.com/search?q=repo%3A10up%2Fwp-scaffold%20%24n%20%3D%20function%20(%20%24function%20)%20%7B&type=code

This function prevents IDE functionality such as go-to defintion and auto-completion and prevents static analyzers and unused code tools from knowing whether the functions are in use

**Comment by darylldoyle** [comment]
Thanks, @tobeycodes. I've added this to the Internal Tools working group agenda to be discussed.
