### ISSUE TITLE
LiveReload is working, but CSS injecting is not

### ISSUE THREAD

**Issue by saltcod** [10up/wp-scaffold#34]
**Description**
Live reloading works in the current setup, what does a full page refresh when there are CSS changes. The expected behavior, and what worked in the old scaffold, is that CSS changes would be injected without a page reload.  

**Steps to Reproduce**
1. $ npm run watch
2. open localhost:300x 
3. Make a css change, save the file
4. See the entire page refresh instead of the css being injected

**Comment by smy315** [comment]
@saltcod fix needs to be made on 10up-toolkit so want to create an issue here https://github.com/10up/10up-toolkit/issues instead?

**Comment by fabiankaegy** [comment]
This can be closed. With the transition to using HMR in 10up-toolkit V3 this no longer is an issue
