### ISSUE TITLE
Adding theme support for better nav widgets and ADA support

### ISSUE THREAD

**Issue by saltnpixels** [10up/wp-scaffold#36]
**Is your enhancement related to a problem? Please describe.**
Menus output as widgets are wrapped in div and are not ADA compliant. 
With WordPress 5.5 this has been fixed. It outputs a nav element, and has aria-labels included.
To use it, it must be added as a theme support.
Currently `navigation-widgets` is not there.

https://make.wordpress.org/core/2020/07/09/accessibility-improvements-to-widgets-outputting-lists-of-links-in-5-5/

In core.php, by adding the following changes we can make sure the menu is output with aria-labels and uses a nav element instead of a div element. 

```php
add_theme_support(
		'html5',
		array(
			'search-form',
			'gallery',
			'navigation-widgets'
		)
	);
```

https://github.com/10up/wp-scaffold/blob/01d71ae09ba9808764e88b21e6be00a9e076bbca/themes/10up-theme/includes/core.php#L59

Would create a nav element in sidebar with aria attributes:

<img width="564" alt="Screen Shot 2021-05-11 at 10 55 56 AM" src="https://user-images.githubusercontent.com/11615474/117837469-7a58e380-b247-11eb-8c38-00388bf0e1f1.png">

**Describe the solution you'd like**

Add it!

**Comment by claytoncollie** [comment]
@saltnpixels Like this? #51 

Since the theme doesnt register any widget areas, I disagree that this should be added by default. As I pointed out in the PR, this could be added since 1) many developers might not know about it and 2) the theme should be accessible by default.
