### ISSUE TITLE
Eslintignore missing on Theme directory

### ISSUE THREAD

**Issue by smy315** [10up/wp-scaffold#37]
Theme directory does not have a eslintignore at the moment. Plugin directory has one (/mu-plugins/10up-plugin/.eslintignore) so copy this one over to the theme?

Also, remove `webpack.config.babel.js` on /mu-plugins/10up-plugin/.eslintignore since it's no longer needed.

Screenshot of eslint showing errors for a third party file placed within vendor folder:
![Screen Shot 2021-05-20 at 9 27 31 AM](https://user-images.githubusercontent.com/2092765/118987051-e7f2c700-b94d-11eb-9ac9-3d406b90d79e.png)

**Comment by claytoncollie** [comment]
@smy315 I added a PR for this issues at #52
