### ISSUE TITLE
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js): TypeError: $ is not a function

### ISSUE THREAD

**Issue by sharazghouri** [10up/wp-scaffold#39]
**Describe the bug**
![image](https://user-images.githubusercontent.com/17900945/119991719-2be76b00-bfe3-11eb-9857-7b4b4add50a9.png)

**Steps to Reproduce**
npm install
npm install -dev
npm run start

**Expected behavior**

CSS file not compiling and giving an error you can see the screeshot. It must be compile smothly.**Screenshots**
![image](https://user-images.githubusercontent.com/17900945/119991719-2be76b00-bfe3-11eb-9857-7b4b4add50a9.png)

**Environment information**
 - Device: 
 - OS: windows
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by sharazghouri** [comment]
An error has gone if I add .babelrc.js with this configuration 

```
module.exports = {
  presets: [
    ['@babel/preset-env', {
      "useBuiltIns": "usage" // do I need this?
    }]
  ],
  "plugins": [
    [
        "@babel/plugin-transform-runtime",
        {
            "corejs": 3 // Refer to the official documentation
          }
    ]
  ]
};module.exports = {
  presets: [
    ['@b
```abel/preset-env', {
      "useBuiltIns": "usage" // do I need this?
    }]
  ],
  "plugins": [
    [
        "@babel/plugin-transform-runtime",
        {
            "corejs": 3 // Refer to the official documentation
          }
    ]
  ]
};

**Comment by turtlepod** [comment]
same issue here.
also using windows

**Comment by fabiankaegy** [comment]
This was a webpack error that was fix
