### ISSUE TITLE
Admin Style vs Editor Style

### ISSUE THREAD

**Issue by smy315** [10up/wp-scaffold#5]
For both theme and plugin, there are admin-style.css and editor-style.css. Do we need both? If we do need to make admin/editor specific style updates, which file we do we update? 

1) /wp-content/themes/10up-theme/assets/css/admin/admin-style.css
2) /wp-content/themes/10up-theme/assets/css/frontend/editor-style.css
3) /wp-content/mu-plugins/10up-plugin/assets/css/admin/admin-style.css
4)  /wp-content/mu-plugins/10up-plugin/assets/css/admin/editor-style.css

If we do remove one, I vote to remove editor-style to stay consistent with JS folder/file name (wp-content/mu-plugins/10up-plugin/assets/js/admin/admin.js).

**Comment by fabiankaegy** [comment]
@smy315 I want to make sure I understand what you want correctly. 

Do you advocate for removing the file just from the plugin or do you advocate for removing the `editor-style` in both cases and only having the `admin-style`? 

If you are talking about the ladder I would advocate against removing one of them. The difference between the two is that the `editor-script` gets enqueued in the editor context only. So everywhere the block editor is being used. (Editor and Widgets Editor). The `admin` css gets enqueued on every `is_admin()` page and therefore is useful for targeting settings pages etc. 

The `editor-styles` entry point should also be scoped to the `.editor-styles-wrapper` class using a Webpack plugin. Which the `admin-styles` should not.

**Comment by smy315** [comment]
@fabiankaegy I am aware of what is happening under the hood and the intent for having two separate files. Concern is usage based on how 10up Scaffold (https://github.com/10up/theme-scaffold) has been utilized the past few years with same structure. I've seen projects where duplicate code are added and on most projects, one is left blank and all the admin/editor styles are added on one directory and leaving the other blank. We actually had a conversation about this internally but don't think anything was done about it. I think most agreed that it feels repetitive.

Also, the path for editor-style.css seems odd being located under /frontend folder. 

One more thing I forgot to mention. Based on the new custom block structure, it looks the example block includes CSS within the block folder: /themes/10up-theme/includes/blocks/example-block/index.css and https://github.com/10up/wp-scaffold/blob/trunk/themes/10up-theme/includes/blocks/example-block/index.js#L19. This also feels repetitive if we keep editor-style.css.

No strong opinion on this except for the /frontend path for editor-style.css 😛 . Having WordPress admin style across 3 different directory doesn't seem right. Will send you some examples via Slack.

**Comment by fabiankaegy** [comment]
@smy315 Yeah I 100% agree :) 

When I looks not at whats there but what would be Ideal I think that in an ideal case there would be one editor css where you can do overrides but not having to re import all the block styles in two places. 

In an ideal Gutenberg world the entire frontend stylesheet would get enqueued in the editor with the editor styles wrapper. And then there is a separate file to override some editor specific styling.


and then the structure could be:
```
assets
    frontend → gets enqueued both in the editor and on the frontend
    admin → gets enqueued on all `is_admin()` sites except for the editor
    editor → gets enqueued in the editor only
```

and having that clear structure might make it a bit more clear.

**Comment by Firestorm980** [comment]
> The editor-styles entry point should also be scoped to the .editor-styles-wrapper class using a Webpack plugin.

and...

> In an ideal Gutenberg world the entire frontend stylesheet would get enqueued in the editor with the editor styles wrapper. And then there is a separate file to override some editor specific styling.

I think it is worth mentioning our transition away from the Webpack plugin has already started via: https://github.com/10up/wp-scaffold/pull/69/files. Use of https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#editor-styles is encouraged now in the manner that the second quote is referencing.

So this issue can fully focus on how to structure the files / directories at this point.

**Comment by fabiankaegy** [comment]
@Firestorm980 thanks for raising this issue again. As of the updates that were made in #69 there is no more `editor-style` file anymore. The frontend stylesheet gets enqueued in the editor and scoped to the `.editor-styles-wrapper` by WordPress Core. WIth no escape hatch. 

Therefore we introduced a new `.editor-style-overrides` that is really only meant to be used to alter the styles in / of the editor itself. These styles are not getting targeted to the `.editor-styles-wrapper`. 

So yeah we can just focus on folder structure. Which I think we can make much more clear. 

I don't understand why blocks are their own directory outside of the frontend folder for example :)
