### ISSUE TITLE
Add ct.css 

### ISSUE THREAD

**Issue by dainemawer** [10up/wp-scaffold#59]
**Describe the solution you'd like**
Harry Roberts recently released a great little CSS utility that helps identify performance issues on sites called `ct.css`.
It is a diagnostic CSS stylesheet that looks something like this: https://csswizardry.com/ct/test/

This has a ton of benefits for adopting a performance culture at 10up where engineers can see with little effort what's being blocked or what can be optimized without adding to JS bloat.

My suggestion here would be to conditionally render `ct.css` behind a query string, say: `?debug_perf=1` which will trigger the stylesheets load.

The goal here is to quickly be able to diagnose what's blocking the rendering pipeline and solve it efficiently.

Great article at Smashing Magazine about this: https://www.smashingmagazine.com/2021/09/css-head-tag/

**Comment by joesnellpdx** [comment]
@dainemawer How I read this, this will be purely conditional and only be reflected with the URL param listed above.

I see no hesitation in adding it to our projects for easy testing. 

Included with this, I'd like to have an update to the upcoming theme readme (maybe add a performance section) that is being added by [@fabiankaegy 's PR](https://github.com/10up/wp-scaffold/pull/60) to add `theme.json`.... unless you think there is a better means of communicating this added functionality to the scaffolding.

**Comment by dainemawer** [comment]
@joesnellpdx that's exactly right - the CSS would not load unless the page was loaded with a URL param. We could also couple this with the `WP_ENVIRONMENT_TYPE` to ensure that this only occurs on `development` for instance. Very happy to add documentation to the `README.md` let me draft a PR!

**Comment by dainemawer** [comment]
@joesnellpdx - have a PR for this: https://github.com/10up/wp-scaffold/pull/61
Not sure who to assign it to, let me know!
