### ISSUE TITLE
Plugin Clean Up

### ISSUE THREAD

**Issue by smy315** [10up/wp-scaffold#6]
Plugin is bloated with theme specific files that should be removed. For example, both the theme and plugin are adding normalize which means that out of the box, 10up WP Scaffold will load normalize two times on a site. This should only be included within the theme.

<img width="859" alt="Screen_Shot_2021-02-04_at_8_23_27_PM-2" src="https://user-images.githubusercontent.com/2092765/106976916-4beada00-6727-11eb-9d67-ce3b5c194964.png">

<img width="934" alt="Screen_Shot_2021-02-04_at_8_23_45_PM-2" src="https://user-images.githubusercontent.com/2092765/106976921-4ee5ca80-6727-11eb-983d-aabf49c1fd43.png">

**Comment by smy315** [comment]
https://github.com/10up/wp-scaffold/pull/11

**Comment by ryanwelcher** [comment]
@smy315 @tlovett1 this looks to have been addressed? Can we close it?

**Comment by smy315** [comment]
Yup https://github.com/10up/wp-scaffold/pull/11 was merged which addressed this issue.
