### ISSUE TITLE
Why does a .gitkeep file have PHP in it?

### ISSUE THREAD

**Issue by benlk** [10up/wp-scaffold#77]
### Describe the bug

The `.gitkeep` file https://github.com/10up/wp-scaffold/blob/trunk/mu-plugins/10up-plugin/includes/classes/.gitkeep contains PHP code.

Is this because:
- the PHP in this file was erroneously added to the existing `.gitkeep` file instead of creating a new `.php` file to contain it? In this case, the file should be renamed.
- the `.gitignore` file was created by copying an existing file elsewhere? In this case, the file should probably have the same contents as other `.gitignore` files in this repository.

### Steps to Reproduce

View https://github.com/10up/wp-scaffold/blob/trunk/mu-plugins/10up-plugin/includes/classes/.gitkeep

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dainemawer** [comment]
My gut tells me this is just an oversight - @tlovett1 any ideas?

**Comment by tlovett1** [comment]
I'm sure this was just an oversight. Feel free to submit a PR emptying the file.

**Comment by barryceelen** [comment]
Fixed in https://github.com/10up/wp-scaffold/pull/136
