### ISSUE TITLE
Composer phpcs lint doesn't work in most cases.

### ISSUE THREAD

**Issue by tylercherpak** [10up/wp-scaffold#81]
### Describe the bug

Since most WordPress projects will have multiple plugins, running `phpcs .` from the wp-content directory will run out of memeory.

### Steps to Reproduce

1. Install a few plugins
2. Run `composer run lint`
3. See error when it runs out of memory

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by darylldoyle** [comment]
This has been fixed by ignoring `/plugins/*` by default and specifically defining the directories we want to analyse.
